2025-05-09 08:07:54,441 INFO    MainThread:212617 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /local/scratch/code/TROPHY/colon_data_analysis/CRIME/Develop/wandb/run-20250509_080754-f9009h71/logs/debug.log
2025-05-09 08:07:54,441 INFO    MainThread:212617 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /local/scratch/code/TROPHY/colon_data_analysis/CRIME/Develop/wandb/run-20250509_080754-f9009h71/logs/debug-internal.log
2025-05-09 08:07:54,441 INFO    MainThread:212617 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x77c1257c5d10>
2025-05-09 08:07:54,441 INFO    MainThread:212617 [wandb_init.py:init():761] calling init triggers
2025-05-09 08:07:54,441 INFO    MainThread:212617 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_config': 1, 'eval_on': 'train', 'num_to_use_per_class': 1000, 'threshold': 0.55, 'assume_model_classifications': False, 'model_class': 'SCNN_TPL3', 'num_training_folds': 2, 'num_val_test_folds': 2, 'prop_to_use': 1, 'sweep_id': 'wh844aab', 'vae_config': {'input_dim': 2403, 'hidden_dim': 256, 'latent_dim': 16, 'output_dim': 2403, 'learning_rate': 0.001, 'num_epochs': 128, 'beta': 0}, 'num_contexts': 21, '_wandb': {}}
2025-05-09 08:07:54,441 INFO    MainThread:212617 [wandb_init.py:init():784] starting backend
2025-05-09 08:07:54,441 INFO    MainThread:212617 [wandb_init.py:init():788] sending inform_init request
2025-05-09 08:07:54,442 INFO    MainThread:212617 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-09 08:07:54,443 INFO    MainThread:212617 [wandb_init.py:init():803] backend started and connected
2025-05-09 08:07:54,448 INFO    MainThread:212617 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-05-09 08:07:54,449 WARNING MsgRouterThr:212617 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-09 08:07:54,480 INFO    MainThread:212617 [wandb_init.py:init():896] updated telemetry
2025-05-09 08:07:54,483 INFO    MsgRouterThr:212617 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
2025-05-09 08:07:54,484 ERROR   MainThread:212617 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 903, in init
    backend.interface.publish_header()
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 99, in publish_header
    self._publish_header(header)
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 283, in _publish_header
    self._publish(rec)
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/tjh200/miniconda3/envs/ml_env/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
